config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  resources :questions
  post '/questions/:id/up', to: 'questions#voteup', as: 'questionup'
  post '/questions/:id/down', to: 'questions#votedown', as: 'questiondown'
  post '/questions/:id/best_answer', to: 'questions#best_answer', as: 'best_answer'
  post '/questions/:id/pingslack', to: 'questions#remind_on_slack', as: 'remind_on_slack'

  resources :answers, only: [:create, :edit, :update, :destroy]
  post '/answers/:id/up', to: 'answers#voteup', as: 'answerup'
  post '/answers/:id/down', to: 'answers#votedown', as: 'answerdown'

  resources :users, only: [:show, :edit, :update]

  resources :comments, only: [:create, :destroy, :update]

  get '/tags', to: 'questions#get_tags_like', as: 'search_tags'

  root 'questions#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
  end

  get '/notloggedin', to: 'sessions#new', as: 'login'
  get '/notallowed', to: 'sessions#denied', as: 'not_allowed'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'amialive', to: 'healthcheck#amialive'
end

app/models/question.rb
class Question < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :first_line_for_slug,
      [:id, :first_line_for_slug]
    ]
  end

  has_many :answers, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy
  belongs_to :best_answer, class_name: "Answer", foreign_key: "best_answer_id", optional: true
  belongs_to :user
  has_many :comments, as: :post, dependent: :destroy
  has_many :user_views, class_name: "UserQuestionView", dependent: :destroy

  acts_as_taggable

  validates :text, presence: true

  def render_question
    @@markdown.render(self.text)
  end

  def first_line
    l = @@markdown.render(self.text.lines.first)
    if l.empty?
      return '<h1>No title</h1>'
    else
      return l
    end
  end

  def first_line_for_slug
    str = self.text.lines.first.slice(0,100).delete '#'
    return str
  end

  def rails_admin_label
    self.first_line_for_slug
  end

  def self.starting_text
    %{# Question title

Enter the details of your question here. Feel free to make use of
markdown syntax if you are familiar with it. Use the preview tab
above to see what it will look like.}
  end

  def self.get_ordered_questions(order, page = 1, search_query = nil)
    case order
    when 'views'
      filtered_order = 'views'
    when 'votes'
      filtered_order = 'total_votes'
    when 'unanswered'
      filtered_order = 'unanswered'
    else
      filtered_order = 'created_at'
    end

    qs = self
    if !search_query.nil? and search_query != ''
      qs = where("match(text) against (?)", search_query)
                     .union(Question.tagged_with(search_query))
    end

    if filtered_order == 'views'
      return qs.left_joins(:user_views).group(:id).order(Arel.sql('COUNT(user_question_views.id) desc')).page(page)
    elsif filtered_order == 'unanswered'
      return qs.order('best_answer_id').page(page)
    else
      return qs.order(filtered_order + ' DESC').page(page)
    end
  end

  def sorted_answers
    sorted = self.answers.sort_by { |a| [-a.total_votes] }
    if !self.best_answer.nil?
      with_best = []
      sorted.each do |a|
        with_best.push(a) unless a.id == self.best_answer.id
      end
      with_best.unshift(self.best_answer)
      sorted = with_best
    end
    return sorted
  end

  def calculate_votes
    self.votes.sum(:vote)
  end

  def all_users_involved
    answers = self.answers.includes(:user, {comments: [:user]})
    user_ids = answers.pluck('users.id')
    user_ids.push(answers.pluck('users_comments.id'))
    user_ids.push(self.comments.includes(:user).pluck('users.id'))
    user_ids.push(self.user.id)
    return User.where(id: user_ids.flatten.to_set)
  end

  def increment_view(user)
    last_visit = self.user_views.where(user: user).first()
    if last_visit.nil? or last_visit.created_at < Time.now - 15.minutes
      self.user_views.create(user: user)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < LoggedinController
  before_action :set_question, except: [:index, :new, :create, :get_tags_like, :show]
  before_action :can_edit_redirect, only: [:edit, :update, :destroy, :best_answer, :remind_on_slack]
  helper_method :can_edit_question

  # GET /questions
  # GET /questions.json
  def index
    @search_query = params[:s]
    @questions = Question.get_ordered_questions(params[:order], params[:page], @search_query)
    # @most_used_tags = ActsAsTaggableOn::Tag.most_used(10)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.friendly.includes({answers: {comments: [:user]}}, {comments: [:user]}).find(params[:id])
    @answer = Answer.new
    @answer.question = @question
    @question.increment_view(current_user)
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.text = Question.starting_text
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(text: question_params['text'])
    set_tags
    @question.user = current_user

    respond_to do |format|
      if @question.save
        if Rails.application.config.slack_notifications
          SlackNotifierJob.perform_later("A new question has been asked: *#{@question.first_line_for_slug.strip}* #{question_url(@question)}")
        end

        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        flash[:alert] = 'There was a problem saving your question.'
        format.html { render :new  }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_tags_like
    if params[:s].nil? || params[:s] == ""
      render json: []
    else
      tag_list = ActsAsTaggableOn::Tag.named_like(params[:s])
      if tag_list.count > 0
        render json: tag_list
      else
        render json: [{:name => params[:s]}]
      end
    end
  end

  def best_answer
    answer = Answer.find(params[:answer_id])
    if answer.question.id != @question.id
      redirect_to @question, alert: 'There was a problem setting the best answer'
    else
      @question.best_answer = answer
      respond_to do |format|
        if @question.save
          format.html { redirect_to @question, notice: 'Best answer was set' }
          format.json { render :show, status: :ok, location: @question }
        else
          flash[:alert] = 'There was a problem saving your question.'
          format.html { redirect_to @question  }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def remind_on_slack
    if Rails.application.config.slack_notifications
      t = @question.last_reminder.nil? ? @question.created_at : @question.last_reminder
      if t < Time.now - 1.hour
        SlackNotifierJob.perform_later("The question still requires a solution, please help if you can: *#{@question.first_line_for_slug.strip}* #{question_url(@question)}")
        notice = 'A reminder has been sent'
        @question.last_reminder = Time.now
        @question.save
      else
        notice = 'You can only remind slack once an hour'
      end
    else
      notice = 'Slack notifications are disabled'
    end

    respond_to do |format|
      format.html { redirect_to @question, notice: notice }
      format.json { render :show, status: :ok, location: @question }
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      @question.text = question_params['text']
      set_tags
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def voteup
    vote = get_user_vote
    if vote.nil?
      add_vote(1)
      @question.update(total_votes: @question.calculate_votes)
    elsif vote.vote != 1
      vote.update(vote: 1)
      @question.update(total_votes: @question.calculate_votes)
    end

    respond_to do |format|
      format.html { redirect_to @question }
      format.json { render :show, location: @question }
    end
  end

  def votedown
    vote = get_user_vote
    if vote.nil?
      add_vote(-1)
      @question.update(total_votes: @question.calculate_votes)
    elsif vote.vote != -1
      vote.update(vote: -1)
      @question.update(total_votes: @question.calculate_votes)
    end

    respond_to do |format|
      format.html { redirect_to @question }
      format.json { render :show, location: @question }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text, :tag_list)
    end

    def can_edit_question
      @question.user == current_user
    end

    def can_edit_redirect
      redirect_to root_path unless can_edit_question
    end

    def get_user_vote
      @question.votes.where(user_id: current_user.id).first
    end

    def add_vote(value)
      vote =  Vote.new
      vote.user = current_user
      vote.vote = value
      @question.votes.push(vote)
    end

    def set_tags
      tag_list = ""
      if !question_params['tag_list'].nil?
        tag_list = question_params['tag_list']
      end
      new_tags = tag_list.split(',').reject { |c| c.empty? }
      old_tags = @question.tags.map(&:name)
      return if new_tags == old_tags
      (old_tags - new_tags).map {|e| @question.tag_list.remove(e)}
      (new_tags - old_tags ).map {|e| @question.tag_list.add e}
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render partial: 'shared/markdown_helper', locals: {model: f} %>

  <div class="form-group">
    <label>Tags</label>
    <input type="hidden" class='form-control' id='tags' name="question[tag_list]" value="<%= @question.tag_list %>" />
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
$('#tags').select2({
    multiple: true,
    minimumInputLength: 1,
    width: '100%',
    id: function(tag){
			return tag.name;
		},
    ajax: {
        url: "<%= url_for search_tags_path %>",
        dataType: 'json',
        quietMillis: 250,
        data: function (term, page) {
            return {
                s: term
            };
        },
        results: function (data, page) {
            return { results: data };
        },
        cache: false
    },
    initSelection: function(element, callback) {
      var data = [];
      if ($(element).val() !== "") {
        var tags = $(element).val().split(',');
        for (var i=0; i < tags.length; i++) {
          data.push({
            name: tags[i].trim()
          });
        }
      }
      callback(data);
    },
    formatResult: function (tag, container) { return '<div>' + tag.name + '</div>'; },
		formatSelection: function (tag) { return tag.name; },
    dropdownCssClass: "bigdrop",
    escapeMarkup: function (m) { return m; }
});
</script>

app/views/questions/_show.html.erb
<div class="question-summary-item card">
  <div class="question-summary-item__content">
    <% if !question.best_answer.nil? %>
      <div class="ribbon-wrapper-green">
        <div class="ribbon-green">
          Answered
        </div>
      </div>
    <% end %>
    <div class="question-summary-item__title">
      <a href="<%= url_for question %>"><%= sanitize question.first_line %></a>
    </div>
    <%= render partial: 'shared/tag_list', locals: {tags: question.tag_list} %>
  </div>
  <div class="question-summary-item__bottom">
    <div class="question-summary-item__bottom__left">
      <div class="question-summary-item__bottom__item">
        <span data-toggle="tooltip" data-placement="top" title="Comments">
          <%= fa_icon 'comments' %> <%= question.answers.count %>
        </span>
      </div>
      <div class="question-summary-item__bottom__item">
        <span data-toggle="tooltip" data-placement="top" title="Votes">
          <%= fa_icon 'check-square-o' %> <%= question.total_votes %>
        </span>
      </div>
      <div class="question-summary-item__bottom__item">
        <span data-toggle="tooltip" data-placement="top" title="Views">
          <%= fa_icon 'eye' %> <%= question.user_views.count() %>
        </span>
      </div>
    </div>
    <div class="question-summary-item__bottom__right">
      <div class="question-summary-item__bottom__item">
        <%= gravatar_tag question.user.email, :size => 20 %> <%= link_to question.user.email, user_path(question.user) %>
      </div>
      <div class="question-summary-item__bottom__item">
        <span data-toggle="tooltip" data-placement="top" title="<%= question.created_at.strftime('%Y-%m-%d %H:%M') %>">
          <%= fa_icon 'calendar' %> <%= time_ago_in_words(question.created_at) %> ago
        </span>
      </div>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <h3>Editing Question</h3>
      <hr/>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="question-list-container">
  <div class="question-list-container__controls">
    <form method="GET">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." name="s" value="<%= @search_query %>">
        <span class="input-group-btn">
          <button class="btn btn-default js-test-search" type="submit">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div>
    </form>

    <%= link_to 'New Question', new_question_path, class: "btn btn-primary" %>

    <%= render 'shared/sorting_controls' %>
  </div>

  <div class="question-list">
    <% @questions.each do |question| %>
      <%= render partial: 'questions/show', locals: {question: question} %>
    <% end %>
  </div>

  <div class="text-center">
    <%= paginate @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <h3>New Question</h3>
      <hr/>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="question-container">

      <div class="card question-container__item">
        <div class="question-container__item__row">
          <div class="question-container__item__side text-center">
            <div>
              <%= voteup questionup_path(@question) %>
            </div>
            <div>
              <strong><%= @question.total_votes %></strong>
            </div>
            <div>
              <%= votedown questiondown_path(@question) %>
            </div>

            <% if can_edit_question %>
              <div>
                <a href="<%= edit_question_url(@question) %>" class="js-test-edit-question">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit"></span>
                </a>
              </div>
              <% if @question.best_answer.nil? %>
                <div>
                  <%= form_tag(remind_on_slack_path(@question.id), method: "post") do %>
                    <button class="btn btn-link" type="submit">
                      <span class="glyphicon glyphicon-retweet text-info" aria-hidden="true" title="Resend Slack notification"></span>
                    </button>
                  <% end %>
                </div>
              <% end %>
              <div>
                <%= link_to @question, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="glyphicon glyphicon-trash text-danger" aria-hidden="true" title="Delete"></span>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="question-container__item__content">
            <div>
              <%= sanitize @question.render_question %>
            </div>

            <div>
              <%= render partial: 'shared/tag_list', locals: {tags: @question.tag_list} %>
            </div>
          </div>
        </div>

        <div class="question-container__item__row">
          <div class="question-container__item__comments">
            <%= render partial: 'comments/list', locals: {obj: @question} %>
          </div>
          <div class="question-container__item__meta">
            <div class="question-container__item__meta__row">
              <%= gravatar_tag @question.user.email, :size => 25 %> <%= link_to @question.user.email, user_path(@question.user) %>
            </div>
            <div class="question-container__item__meta__row">
              <span data-toggle="tooltip" data-placement="top" title="<%= @question.created_at.strftime('%Y-%m-%d %H:%M') %>">
                <%= fa_icon 'calendar' %> <%= time_ago_in_words(@question.created_at) %> ago
              </span>
            </div>
            <div class="question-container__item__meta__row">
              <%= fa_icon 'eye' %> <%= @question.user_views.count() %>
            </div>
          </div>
        </div>
      </div>


      <% @question.sorted_answers.each do |answer| %>
        <div class="card question-container__answer">

          <% if !@question.best_answer.nil? && @question.best_answer.id == answer.id %>
            <div class="card-header card-header--success">
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Best!
            </div>
          <% end %>

          <div class="question-container__item__row">
            <div class="question-container__item__side text-center">
              <div>
                <%= voteup answerup_path(answer) %>
              </div>
              <div>
                <strong><%= answer.total_votes %></strong>
              </div>
              <div>
                <%= votedown answerdown_path(answer) %>
              </div>

              <% if answer.user == current_user %>
                <div>
                  <a href="<%= edit_answer_url(answer) %>">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit"></span>
                  </a>
                </div>
                <div>
                  <%= link_to answer, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <span class="glyphicon glyphicon-trash text-danger" aria-hidden="true" title="Delete"></span>
                  <% end %>
                </div>
              <% end %>

              <% if can_edit_question && (@question.best_answer.nil? || @question.best_answer.id != answer.id) %>
                <div>
                  <%= form_tag(best_answer_path(@question.id), method: "post") do %>
                    <input type="hidden" name="answer_id" value="<%= answer.id %>"/>
                    <button class="btn btn-link" type="submit"><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span></button>
                  <% end %>
                </div>
              <% end %>
            </div>

            <div class="question-container__answer__content">
              <%= sanitize answer.render_answer %>
            </div>
          </div>

          <div class="question-container__item__row">
            <div class="question-container__item__comments">
              <%= render partial: 'comments/list', locals: {obj: answer} %>
            </div>
            <div class="question-container__item__meta">
              <div class="question-container__item__meta__row">
                <%= gravatar_tag answer.user.email, :size => 25 %> <%= link_to answer.user.email, user_path(answer.user) %>
              </div>
              <div class="question-container__item__meta__row">
                <span data-toggle="tooltip" data-placement="top" title="<%= answer.created_at.strftime('%Y-%m-%d %H:%M') %>">
                  <%= fa_icon 'calendar' %> <%= time_ago_in_words(answer.created_at) %> ago
                </span>
              </div>
            </div>
          </div>

        </div>
      <% end %>

      <h4>Your answer</h4>
      <%= render 'answers/form' %>

    </div>
  </div>
</div>