config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  resources :questions
  post '/questions/:id/up', to: 'questions#voteup', as: 'questionup'
  post '/questions/:id/down', to: 'questions#votedown', as: 'questiondown'
  post '/questions/:id/best_answer', to: 'questions#best_answer', as: 'best_answer'
  post '/questions/:id/pingslack', to: 'questions#remind_on_slack', as: 'remind_on_slack'

  resources :answers, only: [:create, :edit, :update, :destroy]
  post '/answers/:id/up', to: 'answers#voteup', as: 'answerup'
  post '/answers/:id/down', to: 'answers#votedown', as: 'answerdown'

  resources :users, only: [:show, :edit, :update]

  resources :comments, only: [:create, :destroy, :update]

  get '/tags', to: 'questions#get_tags_like', as: 'search_tags'

  root 'questions#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
  end

  get '/notloggedin', to: 'sessions#new', as: 'login'
  get '/notallowed', to: 'sessions#denied', as: 'not_allowed'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'amialive', to: 'healthcheck#amialive'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, polymorphic: true

  validates :text, :post, presence: true

  def render_comment
    @@markdown.render(self.text)
  end

  def rails_admin_label
    "#{user.name} comments on #{post_type} ##{post.id}"
  end
end

app/controllers/comments_controller.rb
class CommentsController < LoggedinController
  before_action :set_question, only: [:destroy, :update]

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    if @comment.save
      if @comment.post_type == 'Question'
        question = @comment.post
      else
        question = @comment.post.question
      end

      users_to_email = question.all_users_involved.where(disable_comment_emails: false)
                         .select { |user| user != @comment.user }
      users_to_email.each do |user|
        NotificationMailer.with(comment: @comment, question: question, user: user).new_comment.deliver_later if Rails.application.config.email_notifications
      end

      redirect_to get_redirect_url(@comment), notice: 'Comment was successfully created.'
    else
      flash[:alert] = 'There was a problem creating your comment.'
      redirect_to root_url
    end
  end

  def update
    url = get_redirect_url(@comment)
    if current_user == @comment.user and @comment.update(comment_params)
      redirect_to url, notice: 'Comment was successfully updated.'
    else
      flash[:alert] = 'Updating comment failed.'
      redirect_to url
    end
  end

  def destroy
    url = get_redirect_url(@comment)
    if current_user != @comment.user
      flash[:alert] = 'You cannot delete someone elses comment.'
      redirect_to url
    else
      question = @comment.post
      @comment.destroy
      redirect_to url, notice: 'Comment was successfully destroyed.'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :post_id, :post_type)
    end

    def set_question
      @comment = Comment.find(params[:id])
    end

    def get_redirect_url(comment)
      if comment.post.class.name == "Question"
        return comment.post
      elsif comment.post.class.name == "Answer"
        return comment.post.question
      else
        return root_path
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_list.html.erb
<% obj.comments.each do |comment| %>
  <div class="comment-list__item">
    <div class="comment-list__item__avatar">
      <span data-toggle="tooltip" data-placement="left" data-html="true" title="<%= comment.user.name %><br/><%= time_ago_in_words(comment.created_at) %> ago">
        <%= gravatar_tag comment.user.email, :size => 25 %>
      </span>
    </div>
    <div class="comment-list__item__content" id="comment-<%= comment.id %>-content">
      <%= sanitize comment.render_comment %>
      <% if comment.user == current_user %>
        <div class="comment-list__item__actions">
          <a href="#" class="edit-comment" data-comment-id="<%= comment.id %>">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </a>
          <%= link_to comment, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash text-danger" aria-hidden="true"></span>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if comment.user == current_user %>
      <div class="comment-list__item__textarea hidden" id="comment-<%= comment.id %>-edit">
        <%= form_tag(comment, method: "patch") do %>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Comment..." name="comment[text]" value="<%= comment.text %>">
            <span class="input-group-btn">
              <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span></button>
            </span>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="comment-list__item">
  <div class="comment-list__item__avatar">
  </div>
  <div class="comment-list__item__textarea" id="comment-new">
    <%= form_tag(comments_path, method: "post") do %>
      <input type="hidden" name="comment[post_id]" value="<%= obj.id %>" />
      <input type="hidden" name="comment[post_type]" value="<%= obj.class.name %>" />
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Comment..." name="comment[text]">
        <span class="input-group-btn">
          <button class="btn btn-primary js-test-comment" type="submit">
            <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>