config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  resources :questions
  post '/questions/:id/up', to: 'questions#voteup', as: 'questionup'
  post '/questions/:id/down', to: 'questions#votedown', as: 'questiondown'
  post '/questions/:id/best_answer', to: 'questions#best_answer', as: 'best_answer'
  post '/questions/:id/pingslack', to: 'questions#remind_on_slack', as: 'remind_on_slack'

  resources :answers, only: [:create, :edit, :update, :destroy]
  post '/answers/:id/up', to: 'answers#voteup', as: 'answerup'
  post '/answers/:id/down', to: 'answers#votedown', as: 'answerdown'

  resources :users, only: [:show, :edit, :update]

  resources :comments, only: [:create, :destroy, :update]

  get '/tags', to: 'questions#get_tags_like', as: 'search_tags'

  root 'questions#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
  end

  get '/notloggedin', to: 'sessions#new', as: 'login'
  get '/notallowed', to: 'sessions#denied', as: 'not_allowed'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'amialive', to: 'healthcheck#amialive'
end

app/views/shared/_demo.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="highlight">
      <h2>Welcome to the demo site</h2>
      <p>You are logged in as a test user in order to play around with the functionality of Question Cove. Data will be removed regularly so please do not use this for anything important. To view the source, visit <a href="https://github.com/severest/question-cove">https://github.com/severest/question-cove</a></p>
    </div>
  </div>
</div>

app/views/shared/_markdown_helper.html.erb
<div class="form-group showdown-form">
  <ul class="sorting-list showdown-form-controls">
    <li class="active"><a href="#" data-view="markdown">Markdown</a></li>
    <li><a href="#" data-view="preview">Preview</a></li>
  </ul>

  <%= model.text_area :text, class: 'form-control showdown-edit mde', id: 'markdown' %>

  <div class="showdown-content" id="preview" style="display: none;"></div>
</div>

<p class="help-block pull-right"><strong>**bold**</strong>&nbsp;&nbsp;&nbsp;<i>_italic_</i>&nbsp;&nbsp;&nbsp;<code>`code`</code>&nbsp;&nbsp;&nbsp;>quote&nbsp;&nbsp;&nbsp;&lt;link&gt;</p>



<script>
  var converter = new showdown.Converter();
  $(function () {
    $('.showdown-edit').on('keyup',function () {
      convert(this);
    });

    // allow tab press in textarea
    $('.showdown-edit').on('keydown',function (e) {
      var $this, end, start;
      if (e.keyCode === 9) {
        start = this.selectionStart;
        end = this.selectionEnd;
        $this = $(this);
        $this.val($this.val().substring(0, start) + "\t" + $this.val().substring(end));
        this.selectionStart = this.selectionEnd = start + 1;
        return false;
      }
    });

    convert('.showdown-edit');
  });

  function convert(id) {
    text = $(id).val();
    html = converter.makeHtml(text);
    $('.showdown-content').html(html);
  }

  $('.showdown-form-controls a').click(function (evt) {
    evt.preventDefault();
    $('.showdown-form-controls li').removeClass('active');
    $(evt.target).parent().addClass('active');
    var view = $(evt.target).data('view');
    $('#preview, #markdown').hide();
    $('#' + view).show();
    enableHighlightJS();
  });
</script>

app/views/shared/_most_used_tags.html.erb
<h4>Most used tags</h4>
<div class="list-group">
  <% tag_list.each do |tag| %>
    <a href="<%= url_for questions_path %>?s=<%= tag %>" class="list-group-item"><span class="badge"><%= tag.taggings_count %></span><%= tag.name %></a>
  <% end %>
</div>

app/views/shared/_sorting_controls.html.erb
<ul class="sorting-list">
  <a href="<%= url_for params.slice(:s, :type).merge(order: 'created_at').permit! %>"><li <% if @order == 'created_at' %>class="active"<% end %>>Most recent</li></a>
  <a href="<%= url_for params.slice(:s, :type).merge(order: 'views').permit! %>"><li <% if @order == 'views' %>class="active"<% end %>>Most viewed</li></a>
  <a href="<%= url_for params.slice(:s, :type).merge(order: 'votes').permit! %>"><li <% if @order == 'votes' %>class="active"<% end %>>Most votes</li></a>
  <a href="<%= url_for params.slice(:s, :type).merge(order: 'unanswered').permit! %>"><li <% if @order == 'unanswered' %>class="active"<% end %>>Unanswered</li></a>
</ul>

app/views/shared/_tag_list.html.erb
<div class="tag-list">
  <% tags.each do |tag| %>
    <a href="<%= url_for questions_path %>?s=<%= tag %>"<span class="label label-default label-question-tag"><%= tag %></span></a>
  <% end %>
</div>