config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'
  resources :questions
  post '/questions/:id/up', to: 'questions#voteup', as: 'questionup'
  post '/questions/:id/down', to: 'questions#votedown', as: 'questiondown'
  post '/questions/:id/best_answer', to: 'questions#best_answer', as: 'best_answer'
  post '/questions/:id/pingslack', to: 'questions#remind_on_slack', as: 'remind_on_slack'

  resources :answers, only: [:create, :edit, :update, :destroy]
  post '/answers/:id/up', to: 'answers#voteup', as: 'answerup'
  post '/answers/:id/down', to: 'answers#votedown', as: 'answerdown'

  resources :users, only: [:show, :edit, :update]

  resources :comments, only: [:create, :destroy, :update]

  get '/tags', to: 'questions#get_tags_like', as: 'search_tags'

  root 'questions#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
  end

  get '/notloggedin', to: 'sessions#new', as: 'login'
  get '/notallowed', to: 'sessions#denied', as: 'not_allowed'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'amialive', to: 'healthcheck#amialive'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionCove</title>

  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>

  <script src="//cdnjs.cloudflare.com/ajax/libs/showdown/1.3.0/showdown.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
</head>
<body>

<div class="page">
  <div class="navigation">
    <div class="navigation__brand">
      <%= link_to 'QC', root_path %>
    </div>

    <% if current_user %>
      <div class="navigation__user">
        <div class="dropdown">
          <button class="btn" id="user-dropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= gravatar_tag current_user.email, :size => 35 %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="user-dropdown">
            <li>
              <a href="<%= url_for user_path(current_user) %>">
                Profile
              </a>
            </li>
            <li>
              <a href="<%= url_for edit_user_path(current_user) %>">
                Settings
              </a>
            </li>
            <li>
              <%= link_to 'Logout', logout_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <div class="content">
    <div class="container-fluid">
      <% if flash[:notice] %>
        <div class="flash-alert alert alert-success" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="flash-alert alert alert-danger" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>